name: release

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build the project
        run: npm run build

      - name: Bump version (no tag) and push
        run: |
          # update package.json and package-lock.json, avoid failing on dirty repo
          npm version patch --no-git-tag-version -m "Upgrade version to %s [skip ci]"
          git add package.json package-lock.json || true
          git commit -m "chore(release): bump version [skip ci]" || echo "no changes to commit"
          git push origin HEAD:main --follow-tags